from .JC2 import NODE_CLASS_MAPPINGS as JC2_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JC2_NODE_DISPLAY_NAME_MAPPINGS
from .JCBO import NODE_CLASS_MAPPINGS as JCBO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JCBO_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**JC2_NODE_CLASS_MAPPINGS, **JCBO_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**JC2_NODE_DISPLAY_NAME_MAPPINGS, **JCBO_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]